# Change these first
owner: MJTSoftware # Your GitHub organization or username, where this repository lives
repo: MJT-Uptime # The name of this repository

sites:
  - name: MJTWebsites
    url: https://mjtwebsites.com/

assignees: # Users to assign downtime issues (optional)
  - MJTSoftware

skipDeleteIssues: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.mjtwebsites.com
  # baseUrl: /your-repo-name
  logoUrl: https://mjtwebsites.com/wp-content/uploads/2023/03/MJT-Websites.svg
  name: Uptime Monitors
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
